services:
  backend1:
    build: ./backend1
    hostname: "Server 1"
    restart: always
    ports:
      - "5001:5000"
    cpus: '0.5'
    mem_limit: 128M

  backend2:
    build: ./backend2
    hostname: "Server 2"
    restart: always
    ports:
      - "5002:5000"
    cpus: '0.5'
    mem_limit: 128M


  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
      - backend2
    restart: always