input {
    beats {
        port => 5044
    }
}

filter {
    json {
        source => "message"
        tag_on_failure => ["malformed_json"]
    }

    ruby {
        code => '
            required = [
                "level",
                "service",
                "player_id",
                "player_name",
                "event_type",
                "linked_gate",
                "status",
                "message"
            ]

            missing = required.select { |f| event.get(f).nil? }

            if missing.length > 0
                event.tag("missing_required_fields")
            end
        '
    }

    if [event_type] == "Invalid Gate Request" {
        mutate {
            add_tag => ["suspicious_activity"]
        }
    }

    if [event_type] == "Challenge Failed" {
        mutate {
            add_tag => ["challenge_failed"]
        }
    }
}

output {
    if "malformed_json" in [tags] or
       "missing_required_fields" in [tags] {

        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "linked-verse-errors-%{+YYYY.MM.dd}"
        }

    } else {
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "linked-verse-logs-%{+YYYY.MM.dd}"
        }
    }

    stdout {
        codec => rubydebug
    }
}