services:
  nginx:
    image: nginx:latest
    container_name: hollow_nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - hollow_net

  storage:
    image: minio/minio:latest
    container_name: hollow_storage
    restart: on-failure
    volumes:
      - ./minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hollow_net

  backend:
    build: ./backend
    container_name: hollow_backend
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - storage
    networks:
      - hollow_net

networks:
  hollow_net: