- name: Initial setup
  hosts: all
  roles:
    - docker

- name: Deploy backend
  hosts: backend
  roles:
    - backend
  tags:
    - backend

- name: Deploy frontend
  hosts: frontend
  roles:
    - frontend
  tags:
    - frontend